{"name": "test_invalid_data_creation", "status": "failed", "statusDetails": {"message": "AssertionError: NO ELEMENT IN DOM", "trace": "self = <ui.pages.base_page.BasePage object at 0x113858310>, locator = ('xpath', '//div[text()=\"Incorrect username length\"]'), timeout = 3\n\n    def find(self, locator, timeout=None):\n        try:\n>           s = self.wait(timeout).until(EC.presence_of_all_elements_located(locator))\n\nlocator    = ('xpath', '//div[text()=\"Incorrect username length\"]')\nself       = <ui.pages.base_page.BasePage object at 0x113858310>\ntimeout    = 3\n\nui/pages/base_page.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"eb5b20b9206978297f7aae0434ebd572\")>\nmethod = <selenium.webdriver.support.expected_conditions.presence_of_all_elements_located object at 0x112f962d0>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nend_time   = 1589971416.5016582\nmessage    = ''\nmethod     = <selenium.webdriver.support.expected_conditions.presence_of_all_elements_located object at 0x112f962d0>\nscreen     = None\nself       = <selenium.webdriver.support.wait.WebDriverWait (session=\"eb5b20b9206978297f7aae0434ebd572\")>\nstacktrace = None\nvalue      = []\n\n../../.local/share/virtualenvs/project_qa-eXckkLaZ/lib/python3.7/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_ui_reg_page.TestUIRegPage object at 0x113845850>\n\n    @pytest.mark.UI     #---\n    def test_invalid_data_creation(self):\n        data = {\"username\": \"invalid_very_large_data\", \"password\": \"pass\", \"email\": \"invalid_email\"}\n        self.base_page.get_create_account_page()\n        self.reg_page.create_account(**data)\n        time.sleep(3)\n    \n>       assert (self.base_page.find(self.reg_page.locators.INVALID_NAME_DIV, timeout=3).is_displayed() or\n                self.base_page.find(self.reg_page.locators.INVALID_EMAIL_DIV, timeout=3).is_displayed())\n\ndata       = {'email': 'invalid_email', 'password': 'pass', 'username': 'invalid_very_large_data'}\nself       = <test_ui_reg_page.TestUIRegPage object at 0x113845850>\n\ntests/tests_ui/test_ui_reg_page.py:70: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <ui.pages.base_page.BasePage object at 0x113858310>, locator = ('xpath', '//div[text()=\"Incorrect username length\"]'), timeout = 3\n\n    def find(self, locator, timeout=None):\n        try:\n            s = self.wait(timeout).until(EC.presence_of_all_elements_located(locator))\n            if len(s) == 1:\n                return self.wait(timeout).until(EC.presence_of_element_located(locator))\n            return self.wait(timeout).until(EC.presence_of_all_elements_located(locator))\n        except:\n>           assert False, 'NO ELEMENT IN DOM'\nE           AssertionError: NO ELEMENT IN DOM\n\nlocator    = ('xpath', '//div[text()=\"Incorrect username length\"]')\nself       = <ui.pages.base_page.BasePage object at 0x113858310>\ntimeout    = 3\n\nui/pages/base_page.py:29: AssertionError"}, "start": 1589971404250, "stop": 1589971416751, "uuid": "ed5d671a-28a2-4434-96fc-1cc8bd5cc18a", "historyId": "c774d103c6fe919d37f349aab7edd7d3", "testCaseId": "f46b3ab5f0972f04e5f7dba30285bf60", "fullName": "tests.tests_ui.test_ui_reg_page.TestUIRegPage#test_invalid_data_creation", "labels": [{"name": "tag", "value": "UI"}, {"name": "parentSuite", "value": "tests.tests_ui"}, {"name": "suite", "value": "test_ui_reg_page"}, {"name": "subSuite", "value": "TestUIRegPage"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "2637-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_ui.test_ui_reg_page"}]}