{"name": "test_exist_email_creation", "status": "failed", "statusDetails": {"message": "AssertionError: NO ELEMENT IN DOM", "trace": "self = <ui.pages.base_page.BasePage object at 0x112fd9d50>, locator = ('xpath', '//div[text()=\"User already exist\"]'), timeout = 3\n\n    def find(self, locator, timeout=None):\n        try:\n>           s = self.wait(timeout).until(EC.presence_of_all_elements_located(locator))\n\nlocator    = ('xpath', '//div[text()=\"User already exist\"]')\nself       = <ui.pages.base_page.BasePage object at 0x112fd9d50>\ntimeout    = 3\n\nui/pages/base_page.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"964548c441e919f8a0a1d507e97a5e28\")>\nmethod = <selenium.webdriver.support.expected_conditions.presence_of_all_elements_located object at 0x1138626d0>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nend_time   = 1589971379.2330282\nmessage    = ''\nmethod     = <selenium.webdriver.support.expected_conditions.presence_of_all_elements_located object at 0x1138626d0>\nscreen     = None\nself       = <selenium.webdriver.support.wait.WebDriverWait (session=\"964548c441e919f8a0a1d507e97a5e28\")>\nstacktrace = None\nvalue      = []\n\n../../.local/share/virtualenvs/project_qa-eXckkLaZ/lib/python3.7/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_ui_reg_page.TestUIRegPage object at 0x11380e210>\n\n    @pytest.mark.UI     #---\n    def test_exist_email_creation(self):\n        data = {\"username\": \"name_exict_mail\", \"password\": \"pass\", \"email\": \"valentina@mail.ru\"}\n        self.base_page.get_create_account_page()\n    \n        self.reg_page.create_account(**data)\n    \n>       assert (self.base_page.find(self.reg_page.locators.INVALID_EXIST_USER_DIV, timeout=3).is_displayed() or\n                self.base_page.find(self.reg_page.locators.INVALID_EMAIL_DIV, timeout=3).is_displayed())\n\ndata       = {'email': 'valentina@mail.ru', 'password': 'pass', 'username': 'name_exict_mail'}\nself       = <test_ui_reg_page.TestUIRegPage object at 0x11380e210>\n\ntests/tests_ui/test_ui_reg_page.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <ui.pages.base_page.BasePage object at 0x112fd9d50>, locator = ('xpath', '//div[text()=\"User already exist\"]'), timeout = 3\n\n    def find(self, locator, timeout=None):\n        try:\n            s = self.wait(timeout).until(EC.presence_of_all_elements_located(locator))\n            if len(s) == 1:\n                return self.wait(timeout).until(EC.presence_of_element_located(locator))\n            return self.wait(timeout).until(EC.presence_of_all_elements_located(locator))\n        except:\n>           assert False, 'NO ELEMENT IN DOM'\nE           AssertionError: NO ELEMENT IN DOM\n\nlocator    = ('xpath', '//div[text()=\"User already exist\"]')\nself       = <ui.pages.base_page.BasePage object at 0x112fd9d50>\ntimeout    = 3\n\nui/pages/base_page.py:29: AssertionError"}, "start": 1589971370384, "stop": 1589971379470, "uuid": "51e012ac-a402-4b7c-b0b6-1bfc3e6de829", "historyId": "90a3657eb2c5481e94a95c16c6cf72c7", "testCaseId": "435dc07c65d7720a6b0c76b835f9c280", "fullName": "tests.tests_ui.test_ui_reg_page.TestUIRegPage#test_exist_email_creation", "labels": [{"name": "tag", "value": "UI"}, {"name": "parentSuite", "value": "tests.tests_ui"}, {"name": "suite", "value": "test_ui_reg_page"}, {"name": "subSuite", "value": "TestUIRegPage"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "2637-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_ui.test_ui_reg_page"}]}